# Generated by Django 3.2.5 on 2021-07-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
    ]
