# Generated by Django 3.2.5 on 2021-07-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes_app', '0002_rename_ingredient_id_dishingredient_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
    ]
