# Generated by Django 3.2.5 on 2021-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='orderingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', through='dishes.DishIngredient', to='dishes.Ingredient'),
        ),
    ]
