# Generated by Django 3.2.5 on 2021-07-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20210720_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='di', to='dishes.dish'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='di', to='dishes.ingredient'),
        ),
    ]
