# Generated by Django 3.2.5 on 2021-07-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20210720_2020'),
        ('dishes', '0004_auto_20210723_0926'),
    ]

    operations = [
    ]
